### ISSUE TITLE
where requirement.txt ? TvT

### ISSUE THREAD

**Issue by kelisiya** [ecnuljzhang/brush-your-text#1]

**Comment by kelisiya** [comment]
and when I load text_cfg.yaml , 
yaml.parser.ParserError: while parsing a block mapping
`line 2, column 3,expected <block end>, but found '<scalar>'`

**Comment by ecnuljzhang** [comment]
1. Thank you for pointing it out. The 'requirements.txt' has been uploaded.
2. I haven't seen that error before, and I suspect the issue lies in the incorrect completion of the 'result_path' variable. Here is our 'result_path' for your reference: result_path: "/data2/zlj/results/Thai/pre".
