### ISSUE TITLE
training code 

### ISSUE THREAD

**Issue by yy9568** [ecnuljzhang/brush-your-text#2]
Will u release training codes? thank you.

**Comment by ecnuljzhang** [comment]
Our method is training-free. All that is needed are ["runwayml/stable-diffusion-v1-5"](https://huggingface.co/runwayml/stable-diffusion-v1-5) and ["lllyasviel/sd-controlnet-canny"](https://huggingface.co/lllyasviel/sd-controlnet-canny).
