### ISSUE TITLE
Failed to gen the sketch image using 'synthtext.py'

### ISSUE THREAD

**Issue by Gemini-Left** [ecnuljzhang/brush-your-text#3]
The var 'surf_w' is larger than 'bg_w' in document 'gen.py'.
I try the example of "A welcome sign reads '欢迎来到 AAAAI 2024' of an international conference" in your paper, but encoutered this bug.

![bug](https://github.com/ecnuljzhang/brush-your-text/assets/37464599/d7aa245d-5be3-4501-ad96-a50f08d0b385)

**Comment by ecnuljzhang** [comment]
This code (synthtext.py) is designed for automated sketch image generation, not for generating output images. Based on your error message, it appears you mistakenly used the prompt for sketch image generation, causing the character length required on the sketch image to exceed the 512-pixel limit. When generating sketch images, you should input a single word or phrase, such as "欢迎来到 AAAI 2024."

It is worth noting that this code is structured to generate sketch images containing only one word or phrase, and it does not support line breaks. If you require line breaks, it is recommended to use graphic design software like Photoshop or drawing tools to manually create the sketch image.

**Comment by Gemini-Left** [comment]
Oh, I see. I make it. Thanks a lot for your instruction.
However，I meet another problem now. That is the program cannot find the model of Canny but it does exist.
(I have tryed to use absolute path likes `/workspace/zjs/brush-your-text/checkpoints/sd-controlnet-canny` and reloaded the model, but neither worked)
Could you please tell me what's wrong with it? Is my model in the wrong directory or?
![bug2](https://github.com/ecnuljzhang/brush-your-text/assets/37464599/9a478b12-fd76-4de3-b0d8-53c759b712fd)

**Comment by Gemini-Left** [comment]
Oh，I see. I made it, thanks a lot for your instruction.
