### ISSUE TITLE
Model Unable to Match Generated Image with Text Description, Only Sketch

### ISSUE THREAD

**Issue by ChchNiu** [ecnuljzhang/brush-your-text#5]
Firstly, I would like to express my appreciation for your work on the "Brush Your Text" model. It's an impressive project.
However, I'm encountering an issue where the model can match the sketch input but fails to align the generated image with the text description provided.

Inputs:
Text: "A welcome sign reads Welcome to ECCV 2024 of an international conference"
Sketch image
<img width="241" alt="test" src="https://github.com/ecnuljzhang/brush-your-text/assets/51219924/e4eb5b02-3d1d-4919-9f49-b7fb59d7be2d">

Outputs:
![test-A welcome sign reads Welcome to ECCV 2024 of an international conferencein Russian, fully detailed -0](https://github.com/ecnuljzhang/brush-your-text/assets/51219924/ba1ccf1b-dcad-431e-8e18-6e1871713c89)
![test-A welcome sign reads Welcome to ECCV 2024 of an international conferencein Russian, fully detailed -1](https://github.com/ecnuljzhang/brush-your-text/assets/51219924/1f2a2b74-1d32-4cce-87aa-0abae4413927)
![test-A welcome sign reads Welcome to ECCV 2024 of an international conferencein Russian, fully detailed -2](https://github.com/ecnuljzhang/brush-your-text/assets/51219924/76682e9e-f9dc-44af-a264-45d205840d6f)

Issue:
The model maintains the content from the sketch but the generated image does not match the text description provided.

Could you please provide some insight into why this mismatch occurs? Is it a known limitation or might there be a configuration error on my end?

Thank you for your time and assistance.

**Comment by tsxr** [comment]
I have the same question

**Comment by ecnuljzhang** [comment]
Several situations may lead to the issue you described:

1. PIP not functioning: Have you specified the bounding box for the sketch image?
2. PIP hyperparameters too small, or parameters for classifier-free guidance too small: Please consider slightly increasing them. 

Please try the above approaches and let me know if you have further questions.
